name: udevs_to_do
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.1
  sqflite: ^2.2.6
  flutter_svg: ^2.0.4
  zoom_tap_animation: ^1.1.0
  shared_preferences: ^2.0.20
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/
    - assets/font/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Black.ttf
        - asset: assets/font/Rubik-BlackItalic.ttf
        - asset: assets/font/Rubik-Bold.ttf
        - asset: assets/font/Rubik-BoldItalic.ttf
        - asset: assets/font/Rubik-ExtraBold.ttf
        - asset: assets/font/Rubik-ExtraBoldItalic.ttf
        - asset: assets/font/Rubik-Italic.ttf
        - asset: assets/font/Rubik-Light.ttf
        - asset: assets/font/Rubik-LightItalic.ttf
        - asset: assets/font/Rubik-Medium.ttf
        - asset: assets/font/Rubik-MediumItalic.ttf
        - asset: assets/font/Rubik-Regular.ttf
        - asset: assets/font/Rubik-SemiBold.ttf
        - asset: assets/font/Rubik-SemiBoldItalic.ttf


